### PR TITLE
Implementation full function print in require config

### PR DESCRIPTION
**Pull request by artemkaint**

### CODE REVIEW

**Comment by ChrisWren** [comment]
Is this for a better pretty print?

**Comment by artemkaint** [comment]
no, this code allow to config function in requirejs.config. Old code uses JSON.stringify that removes all function initialization from object.
E.g. 
<pre><code>
test: {
    src: 'main.js',
    dest: 'main.js',
    options: {
      shim: {
        mocha: {
          exports: 'mocha',
          init: function() {
              @mocha.setup(ui: 'bdd');
          }
        }
      }
   }
}
</code></pre>

**Comment by artemkaint** [comment]
add fix for complex config object key (e.x.   dustjs-linkedin)

**Comment by ChrisWren** [comment]
Thanks @artemkaint!

**Pull request merged**
